FROM ubuntu:16.04
# Install prerequisites
RUN apt-get update && apt-get install -y wget curl jq
RUN wget https://github.com/smitthakkar96/telegraf/releases/download/v1.13.2/telegraf.tar.gz
RUN tar xvzf telegraf.tar.gz && rm telegraf.tar.gz
COPY telegraf.conf /etc/telegraf.conf
COPY *.sh /
CMD ["./entrypoint.sh"]
